### ISSUE TITLE
emmet for BEMJSON

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-forum-content-en#14]
There was a thread recently in Russian [on using BEM in medium-sized projects](https://ru.bem.info/forum/520) written by [Nikolay Gromov](https://github.com/nicothin) who complained that writing [BEMJSON](https://en.bem.info/technology/bemjson/) requires more time than writing HTML with a help of `emmet`.

I don't feel the same way about time spent on writing code not in percentage relating to time spent on debugging and thinking over not in absolute terms but I thought that spending time for writing analogue for `emmet` for BEMJSON is good enough task to spend an evening.

It is how this package [bemmet](https://github.com/tadatuta/bemmet) emerged that can expand abbreviations like `b1>__e1*2>b3_theme_islands+_state_active{hello}` into BEMJSON:
```js
{
    block: 'b1',
    content: [
        {
            block: 'b1',
            elem: 'e1',
            content: [
                {
                    block: 'b3',
                    mods: { theme: 'islands' },
                    content: {}
                },
                {
                    block: 'b1',
                    mods: { state: 'active' },
                    content: 'hello'
                }
            ]
        },
        {
            block: 'b1',
            elem: 'e1',
            content: [
                {
                    block: 'b3',
                    mods: { theme: 'islands' },
                    content: {}
                },
                {
                    block: 'b1',
                    mods: { state: 'active' },
                    content: 'hello'
                }
            ]
        }
    ]
}
```

Using options you can configure custom naming — powered by [bem-naming](https://github.com/bem/bem-naming).
`stringify()` method supports indentation options and quotes — powered by [stringify-object](https://www.npmjs.com/package/stringify-object).

You can try `bemmet` in action using [online demo](http://tadatuta.github.io/bemmet/). You can also install it right away into your editor using plugins for [Sublime Text](https://packagecontrol.io/packages/Bemmet) and [Atom](https://atom.io/packages/atom-bemmet).

Would be nice if you can commit with plugins for some other editors.

Good luck!

**Comment by zxqfox** [comment]
Greatly done! Thanks ;-)
