### ISSUE TITLE
What about linter / checker of BEM structure of CSS code ?

### ISSUE THREAD

**Issue by tavriaforever** [bem/bem-forum-content-en#8]
Question from https://github.com/fabm22:
Hi, is there some tooling for checking the structure of CSS code following BEM approach and having and some warnings if there are errors?
Thanks a lot

**Comment by tadatuta** [comment]
@fabm22 Does [postcss-bem-linter](https://github.com/postcss/postcss-bem-linter) solve you task?

**Comment by fabm22** [comment]
It does indeed look like it. Thanks a lot
